---

- name: ping
  hosts: mediawiki
  become: yes
  tasks:
    - name: ping MachineCible
      ping:

# Arborescence
    - name: Creer répertoire de livraison
      file:
        dest: /appli/wikidevops/LIVR
        state: directory

    - name: Creer repertoire du serveur web
      file:
        dest: /appli/projects/md1/nginx
        state: directory

# Outils
    - name: Install required tools
      apt:
        name:
          - unzip
        state: present

#GNUPG
    - name: Add GNUPG
      apt:
        name:
          - gnupg
        state: present

# PHP
    - name: Add the ondrej PHP PPA
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: install PHP
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php5.6
        - php5.6-fpm
        - php5.6-mysql
        - php5.6-xml
        - php5.6-curl
        - php5.6-gd
        - php5.6-intl
        - php5.6-json
        - php5.6-mbstring

    - name: remove apache2
      apt:
        name: apache2
        state: absent
        purge: yes
