---

- name: ping
  hosts: mediawiki
  become: yes
  tasks:
    - name: ping MachineCible
      ping:

# Arborescence
    - name: Creer répertoire de livraison
      file:
        dest: /appli/wikidevops/LIVR
        state: directory

    - name: Creer repertoire du serveur web
      file:
        dest: /appli/projects/md1/nginx
        state: directory

# Outils
    - name: Install required tools
      apt:
        name:
          - unzip
        state: present

#GNUPG
    - name: Add GNUPG
      apt:
        name:
          - gnupg
        state: present

# PHP
    - name: Add the ondrej PHP PPA
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: install PHP
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php5.6
        - php5.6-fpm
        - php5.6-mysql
        - php5.6-xml
        - php5.6-curl
        - php5.6-gd
        - php5.6-intl
        - php5.6-json
        - php5.6-mbstring

    - name: remove apache2
      apt:
        name: apache2
        state: absent
        purge: yes

#Nginx
    - name: install Nginx
      package:
        name: nginx
        state: present

    - name: start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: create nginx config
      template:
        src: templates/nginx/wiki.j2
        dest: /etc/nginx/sites-available/wiki
      notify: restart nginx

# Pare-feu
    - name: pare-feu enable
      ufw:
        state: enabled

    - name: autoriser ssh
      ufw:
        rule: allow
        name: OpenSSH

    - name:
      ufw:
        rule: allow
        name: 'Nginx HTTP'

#MySQL
    - name: Install mysql
    package:
      name: "{{item}}"
      state: present
    loop:
      - mysql-server
      - python-mysqldb

    - name: Create mysqld.cnf
    copy:
      src: templates/mysql/mysqld.cnf.j2
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf

    - name: Start mysql
    service:
      name: mysql
      state: started

    - name: Enable MySQL
    service:
      name: mysql
      enabled: yes

    - name: Generate new root password
    command: openssl rand -hex 7
    args:
      creates: /root/.my.cnf
    register: mysql_new_root_pass

    - name: Remove anonymous users
    mysql_user:
      name: ""
      state: absent
    when: mysql_new_root_pass.changed

    - name: Remove test database
    mysql_db:
      name: test
      state: absent
    when: mysql_new_root_pass.changed

    - name: Output new root password
    debug:
      msg: "New root password is {{mysql_new_root_pass.stdout}}"
    when: mysql_new_root_pass.changed

    - name: Update root password
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{mysql_new_root_pass.stdout}}"
    loop:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
    when: mysql_new_root_pass.changed

    - name: Create my.cnf
    template:
      src: my.cnf.j2
      dest: /root/.my.cnf
    when: mysql_new_root_pass.changed

    - name: Create MySQL database
    mysql_db:
      name: wiki
      state: present
    notify: stop mysql

    - name: Create MySQL user
    mysql_user:
      name: wiki
      host: localhost
      password: password
      priv: wiki.*:ALL

# MediaWiki
    - name: Unarchive wiki_devops.tar.gz
      unarchive:
        src: files/wiki_devops.tar.gz
        dest: /appli/projects/md1/nginx
        mode: 0755
        owner: www-data
        group: www-data

    - name: Installation Mediawiki
      command: php "/appli/projects/md1/nginx/wiki_devops/maintenance/install.php" --dbuser=wiki --dbpass=password --dbname=wiki --dbserver=localhost --dbtype=mysql --scriptpath=/wiki --lang=fr --pass=password wiki wiki

    - name: Import Donnees.xml
      command: php /appli/projects/md1/nginx/wiki_devops/maintenance/importDump.php files/Donnees.xml

    - name: Rebuild recent changes
      command: php /appli/projects/md1/nginx/wiki_devops/maintenance/rebuildrecentchanges.php

    - name: Unarchive dump_image.tar.gz
      unarchive:
        src: files/dump_image.tar.gz
        dest: /appli/projects/md1/nginx
        mode: 0755
        owner: www-data
        group: www-data

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart mysql
      service:
        name: mysql
        state: restarted
