---

- name: ping
  hosts: mediawiki
  become: yes
  tasks:
    - name: ping MachineCible
      ping:

# Arborescence
    - name: Creer répertoire de livraison
      file:
        dest: /appli/wikidevops/LIVR
        state: directory

    - name: Creer repertoire du serveur web
      file:
        dest: /appli/projects/md1/nginx
        state: directory

# Outils
    - name: Install required tools
      apt:
        name:
          - unzip
        state: present

#GNUPG
    - name: Add GNUPG
      apt:
        name:
          - gnupg
        state: present

# PHP
    - name: Add the ondrej PHP PPA
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: install PHP
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php5.6
        - php5.6-fpm
        - php5.6-mysql
        - php5.6-xml
        - php5.6-curl
        - php5.6-gd
        - php5.6-intl
        - php5.6-json
        - php5.6-mbstring

    - name: remove apache2
      apt:
        name: apache2
        state: absent
        purge: yes

#Nginx
    - name: install Nginx
      package:
        name: nginx
        state: present

    - name: start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Check PHP version
      command: php --version
      register: php_version
    - set_fact:
        fpm_sock: /run/php/php5.{{ php_version.stdout.split(" ")[1].split(".")[1] }}-fpm.sock
      when: ansible_distribution == 'Ubuntu'

    - name: create nginx config
      template:
        src: templates/nginx/wiki.j2
        dest: /etc/nginx/sites-available/wiki
      notify: restart nginx

# Pare-feu
    - name: pare-feu enable
      ufw:
        state: enabled

    - name: autoriser ssh
      ufw:
        rule: allow
        name: OpenSSH

    - name:
      ufw:
        rule: allow
        name: 'Nginx HTTP'

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
